
export const ANNOTATION_TYPE_POKEMON = 'ANNOTATION_TYPE_POKEMON';
export const ANNOTATION_TYPE_HUMAN = 'ANNOTATION_TYPE_HUMAN';

export const ANNOTATION_TYPE_ARRAY = [
  ANNOTATION_TYPE_POKEMON,
  ANNOTATION_TYPE_HUMAN,
];
