
export const ANNOTATION_TYPE_POKEMON = 'ANNOTATION_TYPE_POKEMON';
export const ANNOTATION_TYPE_HUMAN = 'ANNOTATION_TYPE_HUMAN';

export const ANNOTATION_TYPE_ARRAY = [
  ANNOTATION_TYPE_POKEMON,
  ANNOTATION_TYPE_HUMAN,
];

export const annotationTypeReadable = (type: string): string => {
  switch (type) {
    case ANNOTATION_TYPE_POKEMON: return 'Pokemon';
    case ANNOTATION_TYPE_HUMAN: return 'Human';
    default: throw new Error(`annotationTypeReadable - unknown type - ${type}`);
  }
};

// http://kaomoji.ru/en/
// JOY and Cats
export const KAOMOJI_ARRAY = [
  // CATS
  '(=^･ω･^=)',
  '(=^･ｪ･^=)',
  '(=①ω①=)',
  '( =ω=)..nyaa',
  '(= ; ｪ ; =)',
  '(=`ω´=)',
  '(=^‥^=)',
  '( =ノωヽ=)',
  '(=⌒‿‿⌒=)',
  '(=^ ◡ ^=)',
  '(=^-ω-^=)',
  'ヾ(=`ω´=)ノ”',
  '(＾• ω •＾)',
  '(/ =ω=)/',
  'ฅ(•ㅅ•❀)ฅ',
  'ฅ(• ɪ •)ฅ',
  'ଲ(ⓛ ω ⓛ)ଲ',
  '(^=◕ᴥ◕=^)',
  'ଲ(ⓛ ω ⓛ)ଲ',
  '(^=◕ᴥ◕=^)',
  '( =ω= )',
  '(^˵◕ω◕˵^)',
  '(^◔ᴥ◔^)',
  '(^◕ᴥ◕^)',
  'ต(=ω=)ต',
  '( Φ ω Φ )',

  // JOY
  '(* ^ ω ^)',
  '(´ ∀ ` *)',
  '٩(◕‿◕｡)۶',
  '☆*:.｡.o(≧▽≦)o.｡.:*☆',
  '(o^▽^o)',
  '(⌒▽⌒)☆',
  '<(￣︶￣)>',
  'ヽ(・∀・)ﾉ',
  '(´｡• ω •｡`)',
  '(￣ω￣)',
  '｀;:゛;｀;･(°ε° )',
  '(o･ω･o)',
  '(＠＾◡＾)',
  'ヽ(*・ω・)ﾉ',
  '(o_ _)ﾉ彡☆',
  '(^人^)',
  '(o´▽`o)',
  '(*´▽`*)',
  '｡ﾟ( ﾟ^∀^ﾟ)ﾟ｡',
  '( ´ ω ` )',
  '(((o(*°▽°*)o)))',
  '(≧◡≦)',
  '(o´∀`o)',
  '(´• ω •`)',
  '(＾▽＾)',
  '(⌒ω⌒)',
  '∑d(°∀°d)',
  '╰(▔∀▔)╯',
  '(─‿‿─)',
  '(*^‿^*)',
  'ヽ(o^ ^o)ﾉ',
  '(✯◡✯)',
  '(◕‿◕)',
  '(*≧ω≦*)',
  '(☆▽☆)',
  '(⌒‿⌒)',
  '＼(≧▽≦)／',
  'ヽ(o＾▽＾o)ノ',
  '(*°▽°*)',
  '٩(｡•́‿•̀｡)۶',
  '(✧ω✧)',
  'ヽ(*⌒▽⌒*)ﾉ',
  '(´｡• ᵕ •｡`)',
  '( ´ ▽ ` )',
  '(￣▽￣)',
  '╰(*´︶`*)╯',
  'ヽ(>∀<☆)ノ',
  'o(≧▽≦)o',
  '(☆ω☆)',
  '(っ˘ω˘ς )',
  '＼(￣▽￣)／',
  '(*¯︶¯*)',
  '＼(＾▽＾)／',
  '٩(◕‿◕)۶',
  '(o˘◡˘o)',
  '\(★ω★)/',
  '\(^ヮ^)/',
  '(〃＾▽＾〃)',
  '(╯✧▽✧)╯',
  'o(>ω<)o',
  'o( ❛ᴗ❛ )o',
  '｡ﾟ(TヮT)ﾟ｡',
  '( ‾́ ◡ ‾́ )',
  '(ﾉ´ヮ`)ﾉ*: ･ﾟ',
  '(b ᵔ▽ᵔ)b',
  '(๑˃ᴗ˂)ﻭ',
  '(๑˘︶˘๑)',
  '( ˙꒳​˙ )',
  '(*꒦ິ꒳꒦ີ)',
  '°˖✧◝(⁰▿⁰)◜✧˖°',
  '(´･ᴗ･ ` )',
  '(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧',
  '(„• ֊ •„)',
  '(.❛ ᴗ ❛.)',
  '(⁀ᗢ⁀)',
  '(￢‿￢ )',
  '(¬‿¬ )',
  '(*￣▽￣)b',
  '( ˙▿˙ )',
  '(¯▿¯)',
];

export const randomKaomoji = () => KAOMOJI_ARRAY[Math.floor(Math.random()*KAOMOJI_ARRAY.length)];
